package main

import "firstwails/scrolling"

type Columns interface {
}

func initCols(cols *scrolling.Columns) {
	cols.AddColumn("ID", "ID", "ID", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("CreateDate", "CreateDate", "CreateDate", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TTNType", "TTNType", "TTNType", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocIdentity", "DocIdentity", "DocIdentity", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocType", "DocType", "DocType", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocNumber", "DocNumber", "DocNumber", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocDate", "DocDate", "DocDate", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocShippingDate", "DocShippingDate", "DocShippingDate", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocBase", "DocBase", "DocBase", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("DocComment", "DocComment", "DocComment", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperType", "ShipperType", "ShipperType", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperClientRegID", "ShipperClientRegID", "ShipperClientRegID", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperInn", "ShipperInn", "ShipperInn", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperKPP", "ShipperKPP", "ShipperKPP", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperFullName", "ShipperFullName", "ShipperFullName", false).SetFiltered(true).ClassValue("").ClassWidth("w-20")
	cols.AddColumn("ShipperShortName", "ShipperShortName", "ShipperShortName", true).SetFiltered(true).ClassValue("").ClassWidth("w-12")
	cols.AddColumn("ShipperCountryCode", "ShipperCountryCode", "ShipperCountryCode", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperRegionCode", "ShipperRegionCode", "ShipperRegionCode", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ShipperDescription", "ShipperDescription", "ShipperDescription", false).SetFiltered(true).ClassValue("").ClassWidth("w-20")
	cols.AddColumn("ConsigneeType", "ConsigneeType", "ConsigneeType", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeClientRegID", "ConsigneeClientRegID", "ConsigneeClientRegID", true).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeInn", "ConsigneeInn", "ConsigneeInn", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeKPP", "ConsigneeKPP", "ConsigneeKPP", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeFullName", "ConsigneeFullName", "ConsigneeFullName", false).SetFiltered(true).ClassValue("").ClassWidth("w-20")
	cols.AddColumn("ConsigneeShortName", "ConsigneeShortName", "ConsigneeShortName", true).SetFiltered(true).ClassValue("").ClassWidth("w-12")
	cols.AddColumn("ConsigneeCountryCode", "ConsigneeCountryCode", "ConsigneeCountryCode", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeRegionCode", "ConsigneeRegionCode", "ConsigneeRegionCode", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("ConsigneeDescription", "ConsigneeDescription", "ConsigneeDescription", false).SetFiltered(true).ClassValue("").ClassWidth("w-20")
	cols.AddColumn("TranType", "TranType", "TranType", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportCompany", "TransportCompany", "TransportCompany", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportCustomer", "TransportCustomer", "TransportCustomer", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportOwnership", "TransportOwnership", "TransportOwnership", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportType", "TransportType", "TransportType", false).SetFiltered(false).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportDriver", "TransportDriver", "TransportDriver", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportTrailer", "TransportTrailer", "TransportTrailer", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportRegNumber", "TransportRegNumber", "TransportRegNumber", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportForwarder", "TransportForwarder", "TransportForwarder", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportLoadPoint", "TransportLoadPoint", "TransportLoadPoint", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportUnloadPoint", "TransportUnloadPoint", "TransportUnloadPoint", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("TransportRedirect", "TransportRedirect", "TransportRedirect", false).SetFiltered(true).ClassValue("").ClassWidth("w-5")
	cols.AddColumn("Version", "Version", "Version", true).SetFiltered(true).ClassValue("").ClassWidth("w-2")
	cols.AddColumn("State", "State", "State", true).SetFiltered(true).ClassValue("").ClassWidth("w-3")
	cols.AddColumn("Status", "Status", "Status", true).SetFiltered(true).ClassValue("").ClassWidth("w-3")
	cols.AddColumn("ReplyID", "ReplyID", "ReplyID", true).SetFiltered(true).ClassValue("").ClassWidth("w-12")
	cols.AddColumn("Archive", "Archive", "Archive", true).SetFiltered(true).ClassValue("").ClassWidth("w-2")
}
