// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package liteboil

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// License is an object representing the database table.
type License struct {
	ClientRegID    string `boil:"client_reg_id" json:"client_reg_id" toml:"client_reg_id" yaml:"client_reg_id"`
	P0000000000111 string `boil:"P0000000000111" json:"P0000000000111" toml:"P0000000000111" yaml:"P0000000000111"`
	P000000000011  string `boil:"P000000000011" json:"P000000000011" toml:"P000000000011" yaml:"P000000000011"`
	P000000000012  string `boil:"P000000000012" json:"P000000000012" toml:"P000000000012" yaml:"P000000000012"`
	P000000000013  string `boil:"P000000000013" json:"P000000000013" toml:"P000000000013" yaml:"P000000000013"`
	P000000000014  string `boil:"P000000000014" json:"P000000000014" toml:"P000000000014" yaml:"P000000000014"`
	IsRetail       int64  `boil:"is_retail" json:"is_retail" toml:"is_retail" yaml:"is_retail"`
	IsWholesale    int64  `boil:"is_wholesale" json:"is_wholesale" toml:"is_wholesale" yaml:"is_wholesale"`
	IsProducer     int64  `boil:"is_producer" json:"is_producer" toml:"is_producer" yaml:"is_producer"`

	R *licenseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L licenseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LicenseColumns = struct {
	ClientRegID    string
	P0000000000111 string
	P000000000011  string
	P000000000012  string
	P000000000013  string
	P000000000014  string
	IsRetail       string
	IsWholesale    string
	IsProducer     string
}{
	ClientRegID:    "client_reg_id",
	P0000000000111: "P0000000000111",
	P000000000011:  "P000000000011",
	P000000000012:  "P000000000012",
	P000000000013:  "P000000000013",
	P000000000014:  "P000000000014",
	IsRetail:       "is_retail",
	IsWholesale:    "is_wholesale",
	IsProducer:     "is_producer",
}

var LicenseTableColumns = struct {
	ClientRegID    string
	P0000000000111 string
	P000000000011  string
	P000000000012  string
	P000000000013  string
	P000000000014  string
	IsRetail       string
	IsWholesale    string
	IsProducer     string
}{
	ClientRegID:    "licenses.client_reg_id",
	P0000000000111: "licenses.P0000000000111",
	P000000000011:  "licenses.P000000000011",
	P000000000012:  "licenses.P000000000012",
	P000000000013:  "licenses.P000000000013",
	P000000000014:  "licenses.P000000000014",
	IsRetail:       "licenses.is_retail",
	IsWholesale:    "licenses.is_wholesale",
	IsProducer:     "licenses.is_producer",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var LicenseWhere = struct {
	ClientRegID    whereHelperstring
	P0000000000111 whereHelperstring
	P000000000011  whereHelperstring
	P000000000012  whereHelperstring
	P000000000013  whereHelperstring
	P000000000014  whereHelperstring
	IsRetail       whereHelperint64
	IsWholesale    whereHelperint64
	IsProducer     whereHelperint64
}{
	ClientRegID:    whereHelperstring{field: "\"licenses\".\"client_reg_id\""},
	P0000000000111: whereHelperstring{field: "\"licenses\".\"P0000000000111\""},
	P000000000011:  whereHelperstring{field: "\"licenses\".\"P000000000011\""},
	P000000000012:  whereHelperstring{field: "\"licenses\".\"P000000000012\""},
	P000000000013:  whereHelperstring{field: "\"licenses\".\"P000000000013\""},
	P000000000014:  whereHelperstring{field: "\"licenses\".\"P000000000014\""},
	IsRetail:       whereHelperint64{field: "\"licenses\".\"is_retail\""},
	IsWholesale:    whereHelperint64{field: "\"licenses\".\"is_wholesale\""},
	IsProducer:     whereHelperint64{field: "\"licenses\".\"is_producer\""},
}

// LicenseRels is where relationship names are stored.
var LicenseRels = struct {
}{}

// licenseR is where relationships are stored.
type licenseR struct {
}

// NewStruct creates a new relationship struct
func (*licenseR) NewStruct() *licenseR {
	return &licenseR{}
}

// licenseL is where Load methods for each relationship are stored.
type licenseL struct{}

var (
	licenseAllColumns            = []string{"client_reg_id", "P0000000000111", "P000000000011", "P000000000012", "P000000000013", "P000000000014", "is_retail", "is_wholesale", "is_producer"}
	licenseColumnsWithoutDefault = []string{"client_reg_id"}
	licenseColumnsWithDefault    = []string{"P0000000000111", "P000000000011", "P000000000012", "P000000000013", "P000000000014", "is_retail", "is_wholesale", "is_producer"}
	licensePrimaryKeyColumns     = []string{"client_reg_id"}
	licenseGeneratedColumns      = []string{}
)

type (
	// LicenseSlice is an alias for a slice of pointers to License.
	// This should almost always be used instead of []License.
	LicenseSlice []*License
	// LicenseHook is the signature for custom License hook methods
	LicenseHook func(context.Context, boil.ContextExecutor, *License) error

	licenseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	licenseType                 = reflect.TypeOf(&License{})
	licenseMapping              = queries.MakeStructMapping(licenseType)
	licensePrimaryKeyMapping, _ = queries.BindMapping(licenseType, licenseMapping, licensePrimaryKeyColumns)
	licenseInsertCacheMut       sync.RWMutex
	licenseInsertCache          = make(map[string]insertCache)
	licenseUpdateCacheMut       sync.RWMutex
	licenseUpdateCache          = make(map[string]updateCache)
	licenseUpsertCacheMut       sync.RWMutex
	licenseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var licenseAfterSelectMu sync.Mutex
var licenseAfterSelectHooks []LicenseHook

var licenseBeforeInsertMu sync.Mutex
var licenseBeforeInsertHooks []LicenseHook
var licenseAfterInsertMu sync.Mutex
var licenseAfterInsertHooks []LicenseHook

var licenseBeforeUpdateMu sync.Mutex
var licenseBeforeUpdateHooks []LicenseHook
var licenseAfterUpdateMu sync.Mutex
var licenseAfterUpdateHooks []LicenseHook

var licenseBeforeDeleteMu sync.Mutex
var licenseBeforeDeleteHooks []LicenseHook
var licenseAfterDeleteMu sync.Mutex
var licenseAfterDeleteHooks []LicenseHook

var licenseBeforeUpsertMu sync.Mutex
var licenseBeforeUpsertHooks []LicenseHook
var licenseAfterUpsertMu sync.Mutex
var licenseAfterUpsertHooks []LicenseHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *License) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *License) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *License) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *License) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *License) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *License) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *License) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *License) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *License) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range licenseAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLicenseHook registers your hook function for all future operations.
func AddLicenseHook(hookPoint boil.HookPoint, licenseHook LicenseHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		licenseAfterSelectMu.Lock()
		licenseAfterSelectHooks = append(licenseAfterSelectHooks, licenseHook)
		licenseAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		licenseBeforeInsertMu.Lock()
		licenseBeforeInsertHooks = append(licenseBeforeInsertHooks, licenseHook)
		licenseBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		licenseAfterInsertMu.Lock()
		licenseAfterInsertHooks = append(licenseAfterInsertHooks, licenseHook)
		licenseAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		licenseBeforeUpdateMu.Lock()
		licenseBeforeUpdateHooks = append(licenseBeforeUpdateHooks, licenseHook)
		licenseBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		licenseAfterUpdateMu.Lock()
		licenseAfterUpdateHooks = append(licenseAfterUpdateHooks, licenseHook)
		licenseAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		licenseBeforeDeleteMu.Lock()
		licenseBeforeDeleteHooks = append(licenseBeforeDeleteHooks, licenseHook)
		licenseBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		licenseAfterDeleteMu.Lock()
		licenseAfterDeleteHooks = append(licenseAfterDeleteHooks, licenseHook)
		licenseAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		licenseBeforeUpsertMu.Lock()
		licenseBeforeUpsertHooks = append(licenseBeforeUpsertHooks, licenseHook)
		licenseBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		licenseAfterUpsertMu.Lock()
		licenseAfterUpsertHooks = append(licenseAfterUpsertHooks, licenseHook)
		licenseAfterUpsertMu.Unlock()
	}
}

// OneG returns a single license record from the query using the global executor.
func (q licenseQuery) OneG(ctx context.Context) (*License, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single license record from the query.
func (q licenseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*License, error) {
	o := &License{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "liteboil: failed to execute a one query for licenses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all License records from the query using the global executor.
func (q licenseQuery) AllG(ctx context.Context) (LicenseSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all License records from the query.
func (q licenseQuery) All(ctx context.Context, exec boil.ContextExecutor) (LicenseSlice, error) {
	var o []*License

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "liteboil: failed to assign all query results to License slice")
	}

	if len(licenseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all License records in the query using the global executor
func (q licenseQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all License records in the query.
func (q licenseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: failed to count licenses rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q licenseQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q licenseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "liteboil: failed to check if licenses exists")
	}

	return count > 0, nil
}

// Licenses retrieves all the records using an executor.
func Licenses(mods ...qm.QueryMod) licenseQuery {
	mods = append(mods, qm.From("\"licenses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"licenses\".*"})
	}

	return licenseQuery{q}
}

// FindLicenseG retrieves a single record by ID.
func FindLicenseG(ctx context.Context, clientRegID string, selectCols ...string) (*License, error) {
	return FindLicense(ctx, boil.GetContextDB(), clientRegID, selectCols...)
}

// FindLicense retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLicense(ctx context.Context, exec boil.ContextExecutor, clientRegID string, selectCols ...string) (*License, error) {
	licenseObj := &License{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"licenses\" where \"client_reg_id\"=?", sel,
	)

	q := queries.Raw(query, clientRegID)

	err := q.Bind(ctx, exec, licenseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "liteboil: unable to select from licenses")
	}

	if err = licenseObj.doAfterSelectHooks(ctx, exec); err != nil {
		return licenseObj, err
	}

	return licenseObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *License) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *License) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("liteboil: no licenses provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(licenseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	licenseInsertCacheMut.RLock()
	cache, cached := licenseInsertCache[key]
	licenseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			licenseAllColumns,
			licenseColumnsWithDefault,
			licenseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(licenseType, licenseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(licenseType, licenseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"licenses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"licenses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "liteboil: unable to insert into licenses")
	}

	if !cached {
		licenseInsertCacheMut.Lock()
		licenseInsertCache[key] = cache
		licenseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single License record using the global executor.
// See Update for more documentation.
func (o *License) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the License.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *License) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	licenseUpdateCacheMut.RLock()
	cache, cached := licenseUpdateCache[key]
	licenseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			licenseAllColumns,
			licensePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("liteboil: unable to update licenses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"licenses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, licensePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(licenseType, licenseMapping, append(wl, licensePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to update licenses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: failed to get rows affected by update for licenses")
	}

	if !cached {
		licenseUpdateCacheMut.Lock()
		licenseUpdateCache[key] = cache
		licenseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q licenseQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q licenseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to update all for licenses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to retrieve rows affected for licenses")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o LicenseSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LicenseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("liteboil: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), licensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"licenses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, licensePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to update all in license slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to retrieve rows affected all in update all license")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *License) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *License) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("liteboil: no licenses provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(licenseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	licenseUpsertCacheMut.RLock()
	cache, cached := licenseUpsertCache[key]
	licenseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			licenseAllColumns,
			licenseColumnsWithDefault,
			licenseColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			licenseAllColumns,
			licensePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("liteboil: unable to upsert licenses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(licensePrimaryKeyColumns))
			copy(conflict, licensePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"licenses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(licenseType, licenseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(licenseType, licenseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "liteboil: unable to upsert licenses")
	}

	if !cached {
		licenseUpsertCacheMut.Lock()
		licenseUpsertCache[key] = cache
		licenseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single License record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *License) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single License record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *License) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("liteboil: no License provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), licensePrimaryKeyMapping)
	sql := "DELETE FROM \"licenses\" WHERE \"client_reg_id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to delete from licenses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: failed to get rows affected by delete for licenses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q licenseQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q licenseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("liteboil: no licenseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to delete all from licenses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: failed to get rows affected by deleteall for licenses")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o LicenseSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LicenseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(licenseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), licensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"licenses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, licensePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: unable to delete all from license slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "liteboil: failed to get rows affected by deleteall for licenses")
	}

	if len(licenseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *License) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("liteboil: no License provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *License) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLicense(ctx, exec, o.ClientRegID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LicenseSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("liteboil: empty LicenseSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LicenseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LicenseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), licensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"licenses\".* FROM \"licenses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, licensePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "liteboil: unable to reload all in LicenseSlice")
	}

	*o = slice

	return nil
}

// LicenseExistsG checks if the License row exists.
func LicenseExistsG(ctx context.Context, clientRegID string) (bool, error) {
	return LicenseExists(ctx, boil.GetContextDB(), clientRegID)
}

// LicenseExists checks if the License row exists.
func LicenseExists(ctx context.Context, exec boil.ContextExecutor, clientRegID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"licenses\" where \"client_reg_id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, clientRegID)
	}
	row := exec.QueryRowContext(ctx, sql, clientRegID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "liteboil: unable to check if licenses exists")
	}

	return exists, nil
}

// Exists checks if the License row exists.
func (o *License) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LicenseExists(ctx, exec, o.ClientRegID)
}
