// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package a3boil

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ProductionResourcesBox is an object representing the database table.
type ProductionResourcesBox struct {
	ID                           int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	IDProductionResources        null.Int64  `boil:"id_production_resources" json:"id_production_resources,omitempty" toml:"id_production_resources" yaml:"id_production_resources,omitempty"`
	IDProductionResourcesPallets null.Int64  `boil:"id_production_resources_pallets" json:"id_production_resources_pallets,omitempty" toml:"id_production_resources_pallets" yaml:"id_production_resources_pallets,omitempty"`
	BoxNumber                    null.String `boil:"box_number" json:"box_number,omitempty" toml:"box_number" yaml:"box_number,omitempty"`

	R *productionResourcesBoxR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L productionResourcesBoxL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProductionResourcesBoxColumns = struct {
	ID                           string
	IDProductionResources        string
	IDProductionResourcesPallets string
	BoxNumber                    string
}{
	ID:                           "id",
	IDProductionResources:        "id_production_resources",
	IDProductionResourcesPallets: "id_production_resources_pallets",
	BoxNumber:                    "box_number",
}

var ProductionResourcesBoxTableColumns = struct {
	ID                           string
	IDProductionResources        string
	IDProductionResourcesPallets string
	BoxNumber                    string
}{
	ID:                           "production_resources_boxes.id",
	IDProductionResources:        "production_resources_boxes.id_production_resources",
	IDProductionResourcesPallets: "production_resources_boxes.id_production_resources_pallets",
	BoxNumber:                    "production_resources_boxes.box_number",
}

// Generated where

var ProductionResourcesBoxWhere = struct {
	ID                           whereHelperint64
	IDProductionResources        whereHelpernull_Int64
	IDProductionResourcesPallets whereHelpernull_Int64
	BoxNumber                    whereHelpernull_String
}{
	ID:                           whereHelperint64{field: "\"production_resources_boxes\".\"id\""},
	IDProductionResources:        whereHelpernull_Int64{field: "\"production_resources_boxes\".\"id_production_resources\""},
	IDProductionResourcesPallets: whereHelpernull_Int64{field: "\"production_resources_boxes\".\"id_production_resources_pallets\""},
	BoxNumber:                    whereHelpernull_String{field: "\"production_resources_boxes\".\"box_number\""},
}

// ProductionResourcesBoxRels is where relationship names are stored.
var ProductionResourcesBoxRels = struct {
}{}

// productionResourcesBoxR is where relationships are stored.
type productionResourcesBoxR struct {
}

// NewStruct creates a new relationship struct
func (*productionResourcesBoxR) NewStruct() *productionResourcesBoxR {
	return &productionResourcesBoxR{}
}

// productionResourcesBoxL is where Load methods for each relationship are stored.
type productionResourcesBoxL struct{}

var (
	productionResourcesBoxAllColumns            = []string{"id", "id_production_resources", "id_production_resources_pallets", "box_number"}
	productionResourcesBoxColumnsWithoutDefault = []string{}
	productionResourcesBoxColumnsWithDefault    = []string{"id", "id_production_resources", "id_production_resources_pallets", "box_number"}
	productionResourcesBoxPrimaryKeyColumns     = []string{"id"}
	productionResourcesBoxGeneratedColumns      = []string{"id"}
)

type (
	// ProductionResourcesBoxSlice is an alias for a slice of pointers to ProductionResourcesBox.
	// This should almost always be used instead of []ProductionResourcesBox.
	ProductionResourcesBoxSlice []*ProductionResourcesBox
	// ProductionResourcesBoxHook is the signature for custom ProductionResourcesBox hook methods
	ProductionResourcesBoxHook func(context.Context, boil.ContextExecutor, *ProductionResourcesBox) error

	productionResourcesBoxQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	productionResourcesBoxType                 = reflect.TypeOf(&ProductionResourcesBox{})
	productionResourcesBoxMapping              = queries.MakeStructMapping(productionResourcesBoxType)
	productionResourcesBoxPrimaryKeyMapping, _ = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, productionResourcesBoxPrimaryKeyColumns)
	productionResourcesBoxInsertCacheMut       sync.RWMutex
	productionResourcesBoxInsertCache          = make(map[string]insertCache)
	productionResourcesBoxUpdateCacheMut       sync.RWMutex
	productionResourcesBoxUpdateCache          = make(map[string]updateCache)
	productionResourcesBoxUpsertCacheMut       sync.RWMutex
	productionResourcesBoxUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var productionResourcesBoxAfterSelectMu sync.Mutex
var productionResourcesBoxAfterSelectHooks []ProductionResourcesBoxHook

var productionResourcesBoxBeforeInsertMu sync.Mutex
var productionResourcesBoxBeforeInsertHooks []ProductionResourcesBoxHook
var productionResourcesBoxAfterInsertMu sync.Mutex
var productionResourcesBoxAfterInsertHooks []ProductionResourcesBoxHook

var productionResourcesBoxBeforeUpdateMu sync.Mutex
var productionResourcesBoxBeforeUpdateHooks []ProductionResourcesBoxHook
var productionResourcesBoxAfterUpdateMu sync.Mutex
var productionResourcesBoxAfterUpdateHooks []ProductionResourcesBoxHook

var productionResourcesBoxBeforeDeleteMu sync.Mutex
var productionResourcesBoxBeforeDeleteHooks []ProductionResourcesBoxHook
var productionResourcesBoxAfterDeleteMu sync.Mutex
var productionResourcesBoxAfterDeleteHooks []ProductionResourcesBoxHook

var productionResourcesBoxBeforeUpsertMu sync.Mutex
var productionResourcesBoxBeforeUpsertHooks []ProductionResourcesBoxHook
var productionResourcesBoxAfterUpsertMu sync.Mutex
var productionResourcesBoxAfterUpsertHooks []ProductionResourcesBoxHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProductionResourcesBox) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProductionResourcesBox) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProductionResourcesBox) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProductionResourcesBox) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProductionResourcesBox) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProductionResourcesBox) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProductionResourcesBox) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProductionResourcesBox) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProductionResourcesBox) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productionResourcesBoxAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProductionResourcesBoxHook registers your hook function for all future operations.
func AddProductionResourcesBoxHook(hookPoint boil.HookPoint, productionResourcesBoxHook ProductionResourcesBoxHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		productionResourcesBoxAfterSelectMu.Lock()
		productionResourcesBoxAfterSelectHooks = append(productionResourcesBoxAfterSelectHooks, productionResourcesBoxHook)
		productionResourcesBoxAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		productionResourcesBoxBeforeInsertMu.Lock()
		productionResourcesBoxBeforeInsertHooks = append(productionResourcesBoxBeforeInsertHooks, productionResourcesBoxHook)
		productionResourcesBoxBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		productionResourcesBoxAfterInsertMu.Lock()
		productionResourcesBoxAfterInsertHooks = append(productionResourcesBoxAfterInsertHooks, productionResourcesBoxHook)
		productionResourcesBoxAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		productionResourcesBoxBeforeUpdateMu.Lock()
		productionResourcesBoxBeforeUpdateHooks = append(productionResourcesBoxBeforeUpdateHooks, productionResourcesBoxHook)
		productionResourcesBoxBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		productionResourcesBoxAfterUpdateMu.Lock()
		productionResourcesBoxAfterUpdateHooks = append(productionResourcesBoxAfterUpdateHooks, productionResourcesBoxHook)
		productionResourcesBoxAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		productionResourcesBoxBeforeDeleteMu.Lock()
		productionResourcesBoxBeforeDeleteHooks = append(productionResourcesBoxBeforeDeleteHooks, productionResourcesBoxHook)
		productionResourcesBoxBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		productionResourcesBoxAfterDeleteMu.Lock()
		productionResourcesBoxAfterDeleteHooks = append(productionResourcesBoxAfterDeleteHooks, productionResourcesBoxHook)
		productionResourcesBoxAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		productionResourcesBoxBeforeUpsertMu.Lock()
		productionResourcesBoxBeforeUpsertHooks = append(productionResourcesBoxBeforeUpsertHooks, productionResourcesBoxHook)
		productionResourcesBoxBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		productionResourcesBoxAfterUpsertMu.Lock()
		productionResourcesBoxAfterUpsertHooks = append(productionResourcesBoxAfterUpsertHooks, productionResourcesBoxHook)
		productionResourcesBoxAfterUpsertMu.Unlock()
	}
}

// OneG returns a single productionResourcesBox record from the query using the global executor.
func (q productionResourcesBoxQuery) OneG(ctx context.Context) (*ProductionResourcesBox, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single productionResourcesBox record from the query.
func (q productionResourcesBoxQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProductionResourcesBox, error) {
	o := &ProductionResourcesBox{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "a3boil: failed to execute a one query for production_resources_boxes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ProductionResourcesBox records from the query using the global executor.
func (q productionResourcesBoxQuery) AllG(ctx context.Context) (ProductionResourcesBoxSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ProductionResourcesBox records from the query.
func (q productionResourcesBoxQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProductionResourcesBoxSlice, error) {
	var o []*ProductionResourcesBox

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "a3boil: failed to assign all query results to ProductionResourcesBox slice")
	}

	if len(productionResourcesBoxAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ProductionResourcesBox records in the query using the global executor
func (q productionResourcesBoxQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ProductionResourcesBox records in the query.
func (q productionResourcesBoxQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: failed to count production_resources_boxes rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q productionResourcesBoxQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q productionResourcesBoxQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "a3boil: failed to check if production_resources_boxes exists")
	}

	return count > 0, nil
}

// ProductionResourcesBoxes retrieves all the records using an executor.
func ProductionResourcesBoxes(mods ...qm.QueryMod) productionResourcesBoxQuery {
	mods = append(mods, qm.From("\"production_resources_boxes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"production_resources_boxes\".*"})
	}

	return productionResourcesBoxQuery{q}
}

// FindProductionResourcesBoxG retrieves a single record by ID.
func FindProductionResourcesBoxG(ctx context.Context, iD int64, selectCols ...string) (*ProductionResourcesBox, error) {
	return FindProductionResourcesBox(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindProductionResourcesBox retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProductionResourcesBox(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ProductionResourcesBox, error) {
	productionResourcesBoxObj := &ProductionResourcesBox{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"production_resources_boxes\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, productionResourcesBoxObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "a3boil: unable to select from production_resources_boxes")
	}

	if err = productionResourcesBoxObj.doAfterSelectHooks(ctx, exec); err != nil {
		return productionResourcesBoxObj, err
	}

	return productionResourcesBoxObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ProductionResourcesBox) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProductionResourcesBox) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("a3boil: no production_resources_boxes provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productionResourcesBoxColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	productionResourcesBoxInsertCacheMut.RLock()
	cache, cached := productionResourcesBoxInsertCache[key]
	productionResourcesBoxInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			productionResourcesBoxAllColumns,
			productionResourcesBoxColumnsWithDefault,
			productionResourcesBoxColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, productionResourcesBoxGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"production_resources_boxes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"production_resources_boxes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "a3boil: unable to insert into production_resources_boxes")
	}

	if !cached {
		productionResourcesBoxInsertCacheMut.Lock()
		productionResourcesBoxInsertCache[key] = cache
		productionResourcesBoxInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ProductionResourcesBox record using the global executor.
// See Update for more documentation.
func (o *ProductionResourcesBox) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ProductionResourcesBox.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProductionResourcesBox) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	productionResourcesBoxUpdateCacheMut.RLock()
	cache, cached := productionResourcesBoxUpdateCache[key]
	productionResourcesBoxUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			productionResourcesBoxAllColumns,
			productionResourcesBoxPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, productionResourcesBoxGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("a3boil: unable to update production_resources_boxes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"production_resources_boxes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, productionResourcesBoxPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, append(wl, productionResourcesBoxPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to update production_resources_boxes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: failed to get rows affected by update for production_resources_boxes")
	}

	if !cached {
		productionResourcesBoxUpdateCacheMut.Lock()
		productionResourcesBoxUpdateCache[key] = cache
		productionResourcesBoxUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q productionResourcesBoxQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q productionResourcesBoxQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to update all for production_resources_boxes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to retrieve rows affected for production_resources_boxes")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ProductionResourcesBoxSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProductionResourcesBoxSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("a3boil: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productionResourcesBoxPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"production_resources_boxes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productionResourcesBoxPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to update all in productionResourcesBox slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to retrieve rows affected all in update all productionResourcesBox")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ProductionResourcesBox) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProductionResourcesBox) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("a3boil: no production_resources_boxes provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productionResourcesBoxColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	productionResourcesBoxUpsertCacheMut.RLock()
	cache, cached := productionResourcesBoxUpsertCache[key]
	productionResourcesBoxUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			productionResourcesBoxAllColumns,
			productionResourcesBoxColumnsWithDefault,
			productionResourcesBoxColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			productionResourcesBoxAllColumns,
			productionResourcesBoxPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("a3boil: unable to upsert production_resources_boxes, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(productionResourcesBoxPrimaryKeyColumns))
			copy(conflict, productionResourcesBoxPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"production_resources_boxes\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(productionResourcesBoxType, productionResourcesBoxMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "a3boil: unable to upsert production_resources_boxes")
	}

	if !cached {
		productionResourcesBoxUpsertCacheMut.Lock()
		productionResourcesBoxUpsertCache[key] = cache
		productionResourcesBoxUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ProductionResourcesBox record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ProductionResourcesBox) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ProductionResourcesBox record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProductionResourcesBox) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("a3boil: no ProductionResourcesBox provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), productionResourcesBoxPrimaryKeyMapping)
	sql := "DELETE FROM \"production_resources_boxes\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to delete from production_resources_boxes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: failed to get rows affected by delete for production_resources_boxes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q productionResourcesBoxQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q productionResourcesBoxQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("a3boil: no productionResourcesBoxQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to delete all from production_resources_boxes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: failed to get rows affected by deleteall for production_resources_boxes")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ProductionResourcesBoxSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProductionResourcesBoxSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(productionResourcesBoxBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productionResourcesBoxPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"production_resources_boxes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productionResourcesBoxPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: unable to delete all from productionResourcesBox slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "a3boil: failed to get rows affected by deleteall for production_resources_boxes")
	}

	if len(productionResourcesBoxAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ProductionResourcesBox) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("a3boil: no ProductionResourcesBox provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProductionResourcesBox) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProductionResourcesBox(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductionResourcesBoxSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("a3boil: empty ProductionResourcesBoxSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductionResourcesBoxSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProductionResourcesBoxSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productionResourcesBoxPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"production_resources_boxes\".* FROM \"production_resources_boxes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productionResourcesBoxPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "a3boil: unable to reload all in ProductionResourcesBoxSlice")
	}

	*o = slice

	return nil
}

// ProductionResourcesBoxExistsG checks if the ProductionResourcesBox row exists.
func ProductionResourcesBoxExistsG(ctx context.Context, iD int64) (bool, error) {
	return ProductionResourcesBoxExists(ctx, boil.GetContextDB(), iD)
}

// ProductionResourcesBoxExists checks if the ProductionResourcesBox row exists.
func ProductionResourcesBoxExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"production_resources_boxes\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "a3boil: unable to check if production_resources_boxes exists")
	}

	return exists, nil
}

// Exists checks if the ProductionResourcesBox row exists.
func (o *ProductionResourcesBox) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProductionResourcesBoxExists(ctx, exec, o.ID)
}
