browser = ''
hostname = '127.0.0.1'
hostport = '55466'
name = ''
output = 'output'
saveconfig = false
utmhost = 'localhost'
utmport = '8088'

[alcogo4]
dbname = ''
driver = 'sqlite'
file = 'alcogo\lite.db'

[alcohelp3]
dbname = ''
driver = 'sqlite'
file = ''

[application]
console = false
dbtype = 'sqlite'
fsrarid = ''
license = 'f7bc886d-bbcd-4ce9-845f-1209d87d406d'
scantimer = 30
startpage = 'dbinfo'

[config]
dbname = ''
driver = 'sqlite'
file = 'config.db'

[layouts]
timelayout = '2006-01-02T15:04:05-0700'
timelayoutclear = '2006.01.02 15:04:05'
timelayoutday = '2006.01.02'
timelayoututc = '2006-01-02T15:04:05'

[mssql]
connection = 'server=localhost;encrypt=disable;user id=;port=1433'
driver = 'mssql'

[sqlite]
driver = 'sqlite'

[trueznak]
dbname = ''
driver = 'sqlite'
file = ''
