browser = ''
hostname = '127.0.0.1'
hostport = '51877'
name = ''
output = 'output'
saveconfig = false
utmhost = 'localhost'
utmport = '8088'

[alcogo4]
dbname = ''
driver = 'sqlite'
file = 'alcogo\lite.db'

[alcohelp3]
dbname = ''
driver = 'sqlite'
file = ''

[application]
console = false
dbtype = 'sqlite'
fsrarid = ''
license = 'f7bc886d-bbcd-4ce9-845f-1209d87d406d'
scantimer = 30
startpage = 'dbinfo'

[config]
dbname = ''
driver = 'sqlite'
file = 'config.db'

[layouts]
timelayout = '2006-01-02T15:04:05-0700'
timelayoutclear = '2006.01.02 15:04:05'
timelayoutday = '2006.01.02'
timelayoututc = '2006-01-02T15:04:05'

[mssql]
connection = 'server=localhost;encrypt=disable;user id=;port=1433'
driver = 'mssql'

[sqlite]
driver = 'sqlite'

[trueclient]
authtime = ''
deviceid = '8fea59e4-3bfc-439c-8e0f-c2517490d2b7'
hashkey = 'C05850BD845B9DD6683F11635F50F73EF3A83130'
layoututc = '2006-01-02T15:04:05'
omsid = '32539e31-c671-4462-8443-3d92b038b0f9'
standgis = 'markirovka.sandbox.crptech.ru'
standsuz = 'suz.sandbox.crptech.ru'
tokengis = ''
tokensuz = ''

[trueznak]
dbname = ''
driver = 'sqlite'
file = ''
